version: '3.2'

networks:
  next-citati:
    external: true

services:
  notifier:
    build:
      context: .
      dockerfile: docker/notifier/Dockerfile
    container_name: next-citati-notifier
    networks:
      - next-citati


  postgresql:
    image: test/postgresql
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: next-citati-postgresql
    command: postgres
    networks:
      - next-citati

#  frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: next-citati-frontend
    networks:
      - next-citati
    ports:
      - "3000:3000"

#  backend service
  backend:
    depends_on:
      - "postgresql"
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: next-citati-backend
    networks:
      - next-citati
    ports:
      - "8000:8000"

  alembic:
    depends_on:
      - "postgresql"
    build:
      context: .
      dockerfile: docker/alembic/Dockerfile
    container_name: next-citati-alembic
    networks:
      - next-citati
