version: '3.2'

networks:
  next-citati:
    external: true

services:
  notifier:
    build:
      context: .
      dockerfile: system/docker/notifier/Dockerfile
    container_name: next-citati-notifier
    networks:
      - next-citati


  postgresql:
    image: test/postgresql
    build:
      context: .
      dockerfile: system/docker/postgres/Dockerfile
    container_name: next-citati-postgresql
    command: postgres
    networks:
      - next-citati

#  frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: ../system/docker/frontend/Dockerfile
    container_name: next-citati-frontend
    networks:
      - next-citati
    ports:
      - "3000:3000"

#  backend service
  backend:
    build:
      context: ./backend
      dockerfile: ../system/docker/backend/Dockerfile
    container_name: next-citati-backend
    networks:
      - next-citati
    ports:
      - "8000:8000"
